version: 2
jobs:
 release:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t simonmassey/ocd-tools:$CIRCLE_TAG .

     # deploy the image
     - run: docker push simonmassey/ocd-tools:$CIRCLE_TAG
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/